version: '3'

services:
  db:
    image: mysql:5.7
    restart: always
    command: ['--default-authentication-plugin=mysql_native_password']
    volumes:
      - "./db_site1:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: omeka
      MYSQL_DATABASE: omeka
      MYSQL_USER: omeka
      MYSQL_PASSWORD: omeka

  omeka:
    depends_on:
      - db
    build: ./
    volumes:
      - "./files_site10:/var/www/html/files"
    ports:
      - "8001:80"
    restart: always
    environment:
      VIRTUAL_HOST: site1.omeka.cdhsc.org
